export const API_ROOT = "/api/v1";
export const STORAGE_KEY = "pulse-ledger-ui-state";
export const DEFAULT_RETRIEVAL_ARTIFACTS_DIR = "artifacts/pytorch_retrieval";

export const CATEGORY_TITLES = {
  education: "Образование",
  travel: "Путешествия",
  electronics: "Технологии",
  entertainment: "Культура",
  food: "Город",
  sports: "Спорт",
  fashion: "Стиль",
  finance: "Финансы",
  home: "Дом",
};

export const SUBCATEGORY_TITLES = {
  coding: "курсы и практикумы",
  design: "дизайн и визуальные школы",
  car_rental: "каршеринг и аренда",
  smartphones: "смартфоны и экосистемы",
  cinema: "кино и премьеры",
  events: "городские события",
  snacks: "быстрые покупки",
  running: "бег и экипировка",
};

export const placementBlueprint = [
  {
    size: "970x250",
    title: "Leaderboard",
    copy: "Большой верхний баннер под шапкой для takeover-дня, запуска акции или флагманской кампании.",
  },
  {
    size: "300x600",
    title: "Right Rail Sticky",
    copy: "Правый rail для охватных историй и длинных сценариев ретаргетинга.",
  },
  {
    size: "728x90",
    title: "In-Feed Midroll",
    copy: "Встраиваемый слот между карточками, который не ломает ритм ленты.",
  },
  {
    size: "Native Card",
    title: "Sponsored Story",
    copy: "Редакционно выглядящая карточка с брендом, CTA и нативной подачей.",
  },
];

export const DEMO_RESPONSE = {
  user_id: "u_00007",
  as_of_date: "2026-04-09",
  score_mode: "value",
  candidate_mode: "retrieval + ranking",
  model_type: "demo-editorial-ranker",
  retrieval_used: true,
  top_k: 8,
  items: [
    {
      banner_id: "bnr_demo_001",
      brand: "SkyJet",
      category: "travel",
      subcategory: "car_rental",
      banner_format: "native",
      campaign_goal: "traffic",
      pred_ctr: 0.081,
      final_score: 0.912,
      cpm_bid: 182.4,
      quality_score: 0.947,
      age_match: 1,
      gender_match: 1,
      interest_match_any: 1,
      interest_match_count: 3,
      banner_ctr_prior: 0.063,
      user_ctr_prior: 0.052,
      user_subcategory_ctr_prior: 0.071,
      user_banner_ctr_prior: 0.048,
      served_impressions_total: 18420,
      served_clicks_total: 931,
      is_active: true,
      landing_page: "https://example.com/travel/car-rental/skyjet",
      retrieval_rank: 1,
    },
    {
      banner_id: "bnr_demo_002",
      brand: "PixelOne",
      category: "electronics",
      subcategory: "smartphones",
      banner_format: "banner",
      campaign_goal: "purchase",
      pred_ctr: 0.067,
      final_score: 0.861,
      cpm_bid: 205.15,
      quality_score: 0.918,
      age_match: 1,
      gender_match: 1,
      interest_match_any: 1,
      interest_match_count: 2,
      banner_ctr_prior: 0.059,
      user_ctr_prior: 0.052,
      user_subcategory_ctr_prior: 0.064,
      user_banner_ctr_prior: 0.045,
      served_impressions_total: 15280,
      served_clicks_total: 774,
      is_active: true,
      landing_page: "https://example.com/electronics/smartphones/pixelone",
      retrieval_rank: 2,
    },
    {
      banner_id: "bnr_demo_003",
      brand: "CodeSpring",
      category: "education",
      subcategory: "coding",
      banner_format: "native",
      campaign_goal: "lead_gen",
      pred_ctr: 0.059,
      final_score: 0.833,
      cpm_bid: 168.9,
      quality_score: 0.902,
      age_match: 1,
      gender_match: 1,
      interest_match_any: 1,
      interest_match_count: 4,
      banner_ctr_prior: 0.055,
      user_ctr_prior: 0.052,
      user_subcategory_ctr_prior: 0.073,
      user_banner_ctr_prior: 0.038,
      served_impressions_total: 12840,
      served_clicks_total: 609,
      is_active: true,
      landing_page: "https://example.com/education/coding/codespring",
      retrieval_rank: 3,
    },
    {
      banner_id: "bnr_demo_004",
      brand: "CityBite",
      category: "food",
      subcategory: "snacks",
      banner_format: "static",
      campaign_goal: "awareness",
      pred_ctr: 0.043,
      final_score: 0.741,
      cpm_bid: 121.6,
      quality_score: 0.876,
      age_match: 1,
      gender_match: 1,
      interest_match_any: 1,
      interest_match_count: 1,
      banner_ctr_prior: 0.041,
      user_ctr_prior: 0.052,
      user_subcategory_ctr_prior: 0.039,
      user_banner_ctr_prior: 0.031,
      served_impressions_total: 21400,
      served_clicks_total: 801,
      is_active: true,
      landing_page: "https://example.com/food/snacks/citybite",
      retrieval_rank: 4,
    },
  ],
};

export const DEMO_BANNERS = [
  {
    banner_id: "bnr_demo_001",
    brand: "SkyJet",
    category: "travel",
    subcategory: "car_rental",
    banner_format: "native",
    campaign_goal: "traffic",
    target_gender: "U",
    target_age_min: 22,
    target_age_max: 45,
    cpm_bid: 182.4,
    quality_score: 0.947,
    created_at: "2026-03-11",
    is_active: true,
    landing_page: "https://example.com/travel/car-rental/skyjet",
  },
  {
    banner_id: "bnr_demo_002",
    brand: "PixelOne",
    category: "electronics",
    subcategory: "smartphones",
    banner_format: "animated",
    campaign_goal: "purchase",
    target_gender: "U",
    target_age_min: 18,
    target_age_max: 39,
    cpm_bid: 205.15,
    quality_score: 0.918,
    created_at: "2026-02-25",
    is_active: true,
    landing_page: "https://example.com/electronics/smartphones/pixelone",
  },
  {
    banner_id: "bnr_demo_003",
    brand: "CodeSpring",
    category: "education",
    subcategory: "coding",
    banner_format: "native",
    campaign_goal: "lead_gen",
    target_gender: "U",
    target_age_min: 19,
    target_age_max: 41,
    cpm_bid: 168.9,
    quality_score: 0.902,
    created_at: "2026-01-19",
    is_active: true,
    landing_page: "https://example.com/education/coding/codespring",
  },
  {
    banner_id: "bnr_demo_004",
    brand: "CityBite",
    category: "food",
    subcategory: "snacks",
    banner_format: "static",
    campaign_goal: "awareness",
    target_gender: "F",
    target_age_min: 20,
    target_age_max: 38,
    cpm_bid: 121.6,
    quality_score: 0.876,
    created_at: "2026-02-08",
    is_active: false,
    landing_page: "https://example.com/food/snacks/citybite",
  },
];

export const DEMO_USERS = [
  {
    user_id: "u_00007",
    age: 29,
    gender: "U",
    city_tier: "tier_1",
    device_os: "ios",
    platform: "mobile_app",
    income_band: "high",
    activity_segment: "power",
    interest_1: "travel",
    interest_2: "gadgets",
    interest_3: "food",
    country: "RU",
    signup_days_ago: 420,
    is_premium: true,
  },
  {
    user_id: "u_00021",
    age: 34,
    gender: "F",
    city_tier: "tier_1",
    device_os: "android",
    platform: "mobile_app",
    income_band: "mid",
    activity_segment: "steady",
    interest_1: "education",
    interest_2: "design",
    interest_3: "cinema",
    country: "RU",
    signup_days_ago: 180,
    is_premium: false,
  },
  {
    user_id: "u_00032",
    age: 24,
    gender: "M",
    city_tier: "tier_2",
    device_os: "ios",
    platform: "web",
    income_band: "mid",
    activity_segment: "active",
    interest_1: "sports",
    interest_2: "fashion",
    interest_3: "electronics",
    country: "KZ",
    signup_days_ago: 90,
    is_premium: true,
  },
  {
    user_id: "u_00057",
    age: 41,
    gender: "U",
    city_tier: "tier_3",
    device_os: "android",
    platform: "mobile_web",
    income_band: "low",
    activity_segment: "casual",
    interest_1: "finance",
    interest_2: "home",
    interest_3: "travel",
    country: "BY",
    signup_days_ago: 760,
    is_premium: false,
  },
];

export const DEFAULT_CONTROLS = {
  userId: "u_00007",
  topK: 8,
  candidateMode: "retrieval + ranking",
  scoreMode: "value",
  retrievalTopN: 60,
  retrievalArtifactsDir: DEFAULT_RETRIEVAL_ARTIFACTS_DIR,
  onlyActive: true,
  excludeSeen: true,
};

export const DEFAULT_BANNER_FILTERS = {
  query: "",
  status: "all",
  sort: "created_desc",
  page: 1,
  pageSize: 8,
};

export const DEFAULT_USER_FILTERS = {
  query: "",
  premium: "all",
  sort: "signup_desc",
  page: 1,
  pageSize: 8,
};
